CREATE TABLE IF NOT EXISTS T_TRADE (
    ID VARCHAR(32) NOT NULL COMMENT '主键ID（UUID）',
    AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '金额（支持负数）',
    CREATE_TIME DATE NOT NULL DEFAULT (CURDATE()) COMMENT '创建日期',
    UPDATE_TIME DATE NOT NULL DEFAULT (CURDATE()) COMMENT '更新日期',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易记录表';
