CREATE TABLE IF NOT EXISTS T_TRADE (
    ID VARCHAR(32) NOT NULL COMMENT '主键ID（UUID）',
    AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '金额（支持负数）',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易记录表';
